# Package Overview
package_name: plant_leave_diseases_model

# Data Files
train_path: train
validation_path: validation
test_path: test

dataset_url: "https://prod-dcd-datasets-public-files-eu-west-1.s3.eu-west-1.amazonaws.com/349ac012-2948-4172-bbba-3bf8f76596fd"
dataset_data_dir: "Plant_leave_diseases_dataset_with_augmentation"
dataset_class_dir: "datasets/classes"
dataset_class_file: "plant_leave_diseases_classes.txt"


model_name: plant_leave_diseases_model
model_save_file: plant_leave_diseases_model_output_v

# Feature engineering parameters
image_size: 
  - 256
  - 256

scaling_factor: 255.0
rotation: 0.1
zoom: 0.2
flip: horizontal

# Set the random seed
random_state: 42

# Alogrithm parameters
input_shape: 
  - 256
  - 256
  - 3

no_of_classes: 39
no_of_img_per_class_test: 50
no_of_img_per_class_train: 50
no_of_img_per_class_val: 50

epochs: 10
batch_size: 32
optimizer: adam
loss: categorical_crossentropy
accuracy_metric: accuracy
verbose: 1
earlystop: 0
monitor: val_loss
save_best_only: True

learning_rate: 0.0001

# Mappings for calss labels
label_mappings: 
  0: cat
  1: dog
  

# MLFlow parameters
run_name : "run-01"

leaf_class_category_mappings:
  Apple___Apple_scab:0
  Apple___Black_rot:1
  Apple___Cedar_apple_rust:2
  Apple___healthy:3
  Background_without_leaves:4
  Blueberry___healthy:5
  Cherry___Powdery_mildew:6
  Cherry___healthy:7
  Corn___Cercospora_leaf_spotGray_leaf_spot:8
  Corn___Common_rust:9
  Corn___Northern_Leaf_Blight:10
  Corn___healthy:11
  Grape___Black_rot:12
  Grape___Esca_(Black_Measles):13
  Grape___Leaf_blight_(Isariopsis_Leaf_Spot):14
  Grape___healthy:15
  Orange___Haunglongbing_(Citrus_greening):16
  Peach___Bacterial_spot:17
  Peach___healthy:18
  Pepper__bell___Bacterial_spot:19
  Pepper__bell___healthy:20
  Potato___Early_blight:21
  Potato___Late_blight:22
  Potato___healthy:23
  Raspberry___healthy:24
  Soybean___healthy:25
  Squash___Powdery_mildew:26
  Strawberry___Leaf_scorch:27
  Strawberry___healthy:28
  Tomato___Bacterial_spot:29
  Tomato___Early_blight:30
  Tomato___Late_blight:31
  Tomato___Leaf_Mold:32
  Tomato___Septoria_leaf_spot:33
  Tomato___Spider_mitesTwo-spotted_spider_mite:34
  Tomato___Target_Spot:35
  Tomato___Tomato_Yellow_Leaf_Curl_Virus:36
  Tomato___Tomato_mosaic_virus:37
  Tomato___healthy:38

leaf_class_master_category_list:
 - Apple___Apple_scab
 - Apple___Black_rot
 - Apple___Cedar_apple_rust
 - Apple___healthy
 - Background_without_leaves
 - Blueberry___healthy
 - Cherry___Powdery_mildew
 - Cherry___healthy
 - Corn___Cercospora_leaf_spotGray_leaf_spot
 - Corn___Common_rust
 - Corn___Northern_Leaf_Blight
 - Corn___healthy
 - Grape___Black_rot
 - Grape___Esca_(Black_Measles)
 - Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
 - Grape___healthy
 - Orange___Haunglongbing_(Citrus_greening)
 - Peach___Bacterial_spot
 - Peach___healthy
 - Pepper__bell___Bacterial_spot
 - Pepper__bell___healthy
 - Potato___Early_blight
 - Potato___Late_blight
 - Potato___healthy
 - Raspberry___healthy
 - Soybean___healthy
 - Squash___Powdery_mildew
 - Strawberry___Leaf_scorch
 - Strawberry___healthy
 - Tomato___Bacterial_spot
 - Tomato___Early_blight
 - Tomato___Late_blight
 - Tomato___Leaf_Mold
 - Tomato___Septoria_leaf_spot
 - Tomato___Spider_mitesTwo-spotted_spider_mite
 - Tomato___Target_Spot
 - Tomato___Tomato_Yellow_Leaf_Curl_Virus
 - Tomato___Tomato_mosaic_virus
 - Tomato___healthy
 
